version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/generic-rw-s3
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
    steps:
      - checkout
      - run:
          name: Create test folder
          command: |
            mkdir -p ${CIRCLE_TEST_REPORTS}/golang
            mkdir -p ${CIRCLE_COVERAGE_REPORT}
      - run:
          name: External Dependancies
          command: |
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/mattn/goveralls
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
            wget https://raw.githubusercontent.com/Financial-Times/upp-coding-standard/v1.0.0/golangci-config/.golangci.yml
      - run:
          name: Import libraries
          command: dep ensure -v -vendor-only
      - run:
          name: Run linters
          command: golangci-lint run --new-from-rev=master --config .golangci.yml
      - run:
          name: Run Tests
          command: |
            go test ./... -race -cover -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
      - run:
          name: Upload Coverage
          command: /go/bin/goveralls -coverprofile=$CIRCLE_COVERAGE_REPORT/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-results
  dockerfile:
    working_directory: /generic-rw-s3
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
