# Values used for the deployed application.
replicaCount: 1
service:
  name: concepts-rw-s3
bucketName: com.ft.upp.normalised-source-concepts.k8s-pub
env:
  - name: RESOURCE_PATH
    value: "concepts"
