# Values used for the deployed application.
replicaCount: 1
service:
  name: generic-rw-s3
  systemCode: upp-generic-rw-s3
bucket:
  key: "generic-rw-s3.bucket"
  # We have a separate bucket in each region on the cluster
  awsRegionKey: "aws.region"
env:
  - name: KAFKA_ADDRESS
    valueFrom:
      configMapKeyRef:
        name: global-config
        key: msk.kafka.broker.url
  - name: KAFKA_CLUSTER_ARN
    valueFrom:
      configMapKeyRef:
        name: global-config
        key: msk.kafka.cluster.arn
  - name: CONSUMER_GROUP
    value: generic-rw-s3
  - name: CONSUMER_TOPIC
    value: ConceptSuggestions
  - name: KAFKA_LAG_TOLERANCE
    value: "120"
  - name: LOG_LEVEL
    value: INFO
  - name: SRC_CONCURRENT_PROCESSING
    value: "true"

serviceAccountName: eksctl-generic-rw-s3-serviceaccount
