# Values used for the deployed application.
replicaCount: 1
service:
  name: generic-rw-s3
bucketName: com.ft.upp.normalised-source-concepts.k8s-pub
env:
  - name: SRC_ADDR
    valueFrom:
      configMapKeyRef:
        name: global-config
        key: kafka.proxy.url.with.protocol
  - name: SRC_GROUP
    value: generic-rw-s3-ConceptSuggestions
  - name: SRC_TOPIC
    value: ConceptSuggestions
  - name: SRC_CONCURRENT_PROCESSING
    value: "true"
